### PR TITLE
[feat ] Blogs Pagination

### PR DESCRIPTION
**Pull request by hstrowd**
Paginates the blogs section of the site in the same manner as blogs shown on the tags pages. Makes a handful of general consistency changes across the application, including ensuring all file names use kebab casing instead of title casing, removing unused props from the Layout component and removing the associated unused data retrieval, etc.

@DLavin23

### CODE REVIEW

**Comment by hstrowd** [comment]
@DLavin23 What did we decide about the capitalization to be used for component file names? I'm happy to go either way and see arguments in both, but would like to take this opportunity to apply whatever we decide to do in a consistent manner at this time so that we have it in place as we move forward. Thanks.

**Comment by DLavin23** [comment]
@hstrowd remind me, is it possible to capitalize all of the component names or does Gatsby not like when you do that? I'd feel a little more comfortable if @tshuck and/or @Shiggiddie weighed in. Do you guys have a strong preference about the way component files are named? (e.g. capitalization vs. kebab case) I know HQ uses Capitalization/TitleCasing for its component names. Do we want to maintain that pattern in this app?

**Comment by Shiggiddie** [comment]
As a principal: When working in a particular framework or language, I believe that framework/language's best practices should trump pre-existing best practices an organization might have based on their work in other framework/languages.

e.g. I don't write my variable names `thisVariable` in `.rb` files just because I am more comfortable writing JS.

Therefore, this being a Gatsby project, we should follow Gatsby best practices.
[Taking a look at their example app](https://github.com/gatsbyjs/gatsby-starter-blog/tree/master/src), it is clear the Gatsby team is of the mind that Component/Template filenames should be kebab cased.

**Comment by sisk** [comment]
This is literally the first time I heard the term "kebab-cased" and I did a serious double-take.

And now I want [souvlaki](https://en.wikipedia.org/wiki/Souvlaki). Damn you, Sean.

**Comment by hstrowd** [comment]
@DLavin23 In my initial investigation into this I found that I ran into problems in trying to rename the pages (i.e. modules within `/src/pages`) to use title casing. I believe I was able to successfully apply title casing to all component files but can't recall if I even tried renaming the template file after running into problems with the pages.

@Shiggiddie I find kebab casing to be a common file naming pattern across most of the JS projects and libraries I work in. As a result when a project mixes files between formats I find I'm more likely to get tripped up on this. So while I'm sure there are exceptions to the rule, I tend to agree with your assessment and would recommend we use kebab casing for the file names consistently throughout this application.

Any opposition to this approach? If not, I'll plan to make this change and get it merged. I have another PR chomping at the heels of this one. Thanks.

**Comment by hstrowd** [comment]
I'll incorporate the file name change to kebab case into a subsequent PR.

**Pull request merged**
